// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtwfhzzsrlwwjgezbcfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0d2Zoenpzcmx3d2pnZXpiY2ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTU5MTEsImV4cCI6MjA3MjY3MTkxMX0.TPrH_cliKe_xCPgscAew0DjuSXN0ojwZoIl67MxP8TA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});